# Generated by Django 3.1.7 on 2021-03-18 02:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.CharField(default='', max_length=32)),
                ('nid', models.CharField(default='', max_length=32)),
                ('type', models.CharField(default='', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Requestments',
            fields=[
                ('rid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=128, verbose_name='名称')),
                ('project_code', models.CharField(default='', max_length=32, null=True, verbose_name='项目编号')),
                ('price', models.FloatField(null=True, verbose_name='项目预算')),
                ('deadline', models.DateTimeField(null=True, verbose_name='投标截止日期')),
                ('agent', models.CharField(default='', max_length=32, null=True, verbose_name='招标代理机构')),
                ('client', models.CharField(default='', max_length=32, null=True, verbose_name='采购人')),
                ('area', models.CharField(choices=[('szq', '市直'), ('pjq', '蓬江区'), ('jhq', '江海区'), ('xhq', '新会区'), ('tss', '台山市'), ('kps', '开平市'), ('eps', '恩平市'), ('hss', '鹤山市')], default='', max_length=16, null=True, verbose_name='市/区')),
                ('url', models.URLField(blank=True, null=True, verbose_name='原网站链接')),
                ('pdf', models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='招标文件链接')),
                ('pubdate', models.DateTimeField(null=True, verbose_name='发布时间')),
                ('join_time', models.DateTimeField(auto_now=True)),
                ('last_update_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tagmap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagid', models.CharField(default='', max_length=64)),
                ('rid', models.CharField(default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagid', models.CharField(default=uuid.uuid4, max_length=64, unique=True)),
                ('tag', models.CharField(default='', max_length=32)),
                ('num', models.IntegerField(default=0)),
            ],
        ),
    ]
